<?php

namespace App\Services\Admin;

use App\Repositories\FeedstockRepository;
use Exception;
use Prettus\Validator\Exceptions\ValidatorException;

class FeedstockService {
    /**
     * @var FeedstockRepository
     */
    private FeedstockRepository $feedStockRepository;

    public function __construct(FeedstockRepository $feedStockRepository)
    {
        $this->feedStockRepository = $feedStockRepository;
    }

    public function all(?bool $paginate = false)
    {
        return $paginate
            ? $this->feedStockRepository->paginate()
            : $this->feedStockRepository->all();
    }

    /**
     * @throws Exception
     */
    public function show(int $id)
    {
        return $this->feedStockRepository->find($id);
    }

    /**
     * @throws ValidatorException
     * @throws Exception
     */
    public function store(array $data)
    {
        try {
            return $this->feedStockRepository->create($data);
        } catch (Exception $exception) {
            throw new Exception($exception->getMessage());
        }
    }

    /**
     * @throws Exception
     */
    public function update(array $data, int $id)
    {
        $service = $this->feedStockRepository->find($id);
        if (!$service) {
            throw new Exception('Insumo nÃ£o encontrado.');
        }
        try {
            return $this->feedStockRepository->update($data, $id);
        } catch (Exception $exception) {
            throw new Exception($exception->getMessage());
        }
    }

    /**
     * @throws Exception
     */
    public function destroy(int $id): void
    {
        $service = $this->feedStockRepository->find($id);
        if (!$service) {
            throw new Exception('Insumo nÃ£o encontrado.');
        }
        try {
            $this->feedStockRepository->delete($id);
        } catch (Exception $exception) {
            throw new Exception($exception->getMessage());
        }
    }
}
